/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { X } from 'lucide-react';
import { useTranslation } from '../../utils/i18n';

export function LegalModal({
  type,
  onClose,
  isLightTheme,
  surfaceClass,
  titleClass,
  mutedClass
}: {
  type: 'eula' | 'privacy' | 'licenses';
  onClose: () => void;
  isLightTheme: boolean;
  surfaceClass: string;
  titleClass: string;
  mutedClass: string;
}) {
  const { lang } = useTranslation();
  const getModalData = () => {
    switch (type) {
      case 'eula':
        return {
          title: lang === 'tr' ? 'Kullanım Koşulları (EULA)' : 'Terms of Use (EULA)',
          content: lang === 'tr' ? `VELOX - SON KULLANICI LİSANS SÖZLEŞMESİ (EULA)

Son Güncelleme: 04 Temmuz 2026

Bu Son Kullanıcı Lisans Sözleşmesi ("Sözleşme"), Vellium tarafından geliştirilen Velox yazılımı ("Yazılım") için sizinle ("Kullanıcı") Vellium arasında yapılan yasal bir anlaşmadır.

1. LİSANS VERİLMESİ
Vellium, bu Yazılımı kişisel veya ticari kullanımınız için münhasır olmayan, devredilemeyen, sınırlı bir lisansla bu Sözleşme koşulları çerçevesinde kullanma hakkı vermektedir.

2. MÜLKİYET VE FİKRİ MÜLKİYET
Yazılımın tüm telif hakları, ticari markaları, fikri mülkiyet ve patent hakları Vellium'a aittir. Yazılım lisanslanmıştır, satılmamıştır. Kodların kopyalanması, tersine mühendislik yapılması, kaynak koda dönüştürülmesi veya izinsiz dağıtılması kesinlikle yasaktır.

3. HİZMET KALİTESİ VE SORUMLULUK SINIRLANDIRILMASI
Yazılım "olduğu gibi" ve "kullanılabilir olduğu sürece" esasıyla sunulmaktadır. Vellium, yazılımın hatasız çalışacağını garanti etmez. Yapay zeka modülü (Gemini API entegrasyonu) tarafından üretilen özetler, kavramsal içerikler ve sorular bilgi amaçlı olup nihai yasal veya profesyonel kararlarda kaynak gösterilemez; tüm sorumluluk kullanıcıya aittir.

4. İPTAL VE FESİH
Bu sözleşme, yazılımı cihazınızdan kaldırana kadar geçerlidir. Sözleşme koşullarına aykırı hareket edilmesi durumunda lisansınız Vellium tarafından tek taraflı olarak feshedilebilir.`
          : `VELOX - END USER LICENSE AGREEMENT (EULA)

Last Updated: July 04, 2026

This End User License Agreement ("Agreement") is a legal agreement between you ("User") and Vellium for the Velox software ("Software") developed by Vellium.

1. LICENSE GRANT
Vellium grants you a non-exclusive, non-transferable, limited license to use this Software for personal or commercial use in accordance with the terms of this Agreement.

2. OWNERSHIP AND INTELLECTUAL PROPERTY
All copyrights, trademarks, intellectual property and patent rights of the Software belong to Vellium. The Software is licensed, not sold. Copying, reverse engineering, decompiling or unauthorized distribution of codes is strictly prohibited.

3. QUALITY OF SERVICE AND LIMITATION OF LIABILITY
The Software is provided on an "as is" and "as available" basis. Vellium does not guarantee that the software will run error-free. Summaries, conceptual content and questions generated by the AI module (Gemini API integration) are for informational purposes and cannot be cited in final legal or professional decisions; all responsibility belongs to the user.

4. CANCELLATION AND TERMINATION
This agreement is valid until you remove the software from your device. In case of violation of the Agreement terms, your license may be unilaterally terminated by Vellium.`
        };
      case 'privacy':
        return {
          title: lang === 'tr' ? 'Gizlilik Politikası' : 'Privacy Policy',
          content: lang === 'tr' ? `VELOX - GİZLİLİK POLİTİKASI

Son Güncelleme: 04 Temmuz 2026

Velox olarak gizliliğinize son derece saygı duyuyoruz. Bu politika, uygulamamızı kullandığınızda verilerinizin nasıl yönetildiğini açıklamaktadır.

1. YEREL ÖNCELİKLİ (LOCAL-FIRST) VERİ DEPOLAMA
Uygulamaya eklediğiniz tüm belgeler, yazdığınız notlar, okuma süreleriniz, hız istatistikleriniz ve tercihleriniz tamamen cihazınızın yerel depolama alanında (IndexedDB ve localStorage üzerinde) saklanır. Sunucularımıza hiçbir belgeniz veya not içeriğiniz gönderilmez veya saklanmaz.

2. YAPAY ZEKA HİZMETLERİ VE API KULLANIMI
Yapay zeka analiz araçları (Özet, Zorluk Analizi, Kelime Sözlüğü ve Soru Aksiyonları) isteğe bağlıdır. Bir yapay zeka sağlayıcısı (Gemini, OpenAI, Claude veya Lokal Model) tanımladığınızda, seçtiğiniz belgenin analizi için ilgili sağlayıcının API uç noktalarına istek gönderilir. Bu istekler tamamen şifrelenmiş HTTPS kanalları üzerinden yapılır. Gönderilen veriler Vellium veya Velox tarafından kaydedilmez.

3. ÜÇÜNCÜ TARAF HİZMETLER VE ÇEREZLER
Velox, hiçbir kullanıcı takip kütüphanesi, analiz aracı (analytics) veya reklam izleyicisi barındırmamaktadır. Tamamen temiz ve izleyicisiz bir yerel masaüstü uygulamasıdır.

4. BİZE ULAŞIN
Gizlilik politikamızla ilgili sorularınız için vellium.dev web sitesi üzerinden bizimle iletişime geçebilirsiniz.`
          : `VELOX - PRIVACY POLICY

Last Updated: July 04, 2026

At Velox, we highly respect your privacy. This policy explains how your data is managed when you use our application.

1. LOCAL-FIRST DATA STORAGE
All documents you add to the application, notes you write, reading durations, speed statistics and preferences are stored entirely in your device's local storage (on IndexedDB and localStorage). No documents or note content are sent or stored on our servers.

2. AI SERVICES AND API USAGE
AI analysis tools (Summary, Difficulty Analysis, Dictionary and Question Actions) are optional. When you configure an AI provider (Gemini, OpenAI, Claude or Local Model), requests are sent to the provider's API endpoints to analyze the selected document. These requests are made via fully encrypted HTTPS channels. Sent data is not saved by Vellium or Velox.

3. THIRD PARTY SERVICES AND COOKIES
Velox does not contain any user tracking libraries, analytics tools or ad trackers. It is a completely clean and tracker-free local desktop application.

4. CONTACT US
For questions about our privacy policy, you can contact us via the vellium.dev website.`
        };
      case 'licenses':
        return {
          title: lang === 'tr' ? 'Açık Kaynak Lisansları' : 'Open Source Licenses',
          content: lang === 'tr' ? `VELOX - ÜÇÜNCÜ PARTİ YAZILIM BİLDİRİMLERİ

Velox, aşağıdaki açık kaynak kodlu kütüphaneleri ve yazılımları kullanmaktadır. Katkılarından dolayı tüm geliştiricilere teşekkür ederiz.

1. React (MIT Lisansı)
Copyright © Meta Platforms, Inc. and affiliates.

2. Zustand (MIT Lisansı)
Copyright © 2019-2024 Daishi Kato.

3. Recharts (MIT Lisansı)
Copyright © 2015-present Recharts Group.

4. Lucide React (ISC Lisansı)
Copyright © 2020 lucide-react contributors.

5. Mammoth (BSD 2-Clause Lisansı)
Copyright © 2012-2024 Michael Stephens.

6. JSZip (MIT Lisansı)
Copyright © 2009-2016 Stuart Knightley.

7. Motion (MIT Lisansı)
Copyright © 2018 Framer B.V.

8. Vite (MIT Lisansı)
Copyright © 2019-present, Ygritte and Vite contributors.`
          : `VELOX - THIRD PARTY SOFTWARE NOTICES

Velox uses the following open source libraries and software. We thank all developers for their contributions.

1. React (MIT License)
Copyright © Meta Platforms, Inc. and affiliates.

2. Zustand (MIT License)
Copyright © 2019-2024 Daishi Kato.

3. Recharts (MIT License)
Copyright © 2015-present Recharts Group.

4. Lucide React (ISC License)
Copyright © 2020 lucide-react contributors.

5. Mammoth (BSD 2-Clause License)
Copyright © 2012-2024 Michael Stephens.

6. JSZip (MIT License)
Copyright © 2009-2016 Stuart Knightley.

7. Motion (MIT License)
Copyright © 2018 Framer B.V.

8. Vite (MIT License)
Copyright © 2019-present, Ygritte and Vite contributors.`
        };
    }
  };

  const data = getModalData();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 backdrop-blur-md bg-stone-900/40 dark:bg-black/60">
      <div className={`w-full max-w-2xl max-h-[80vh] overflow-hidden rounded-3xl border flex flex-col shadow-2xl ${surfaceClass}`}>
        {/* Modal Header */}
        <div className="p-5 border-b border-stone-200 dark:border-zinc-800 flex justify-between items-center">
          <h3 className={`text-base font-black ${titleClass}`}>{data.title}</h3>
          <button
            onClick={onClose}
            className={`p-1.5 rounded-lg border hover:opacity-80 ${isLightTheme ? 'border-stone-200 bg-white text-stone-900' : 'border-zinc-800 bg-zinc-950 text-zinc-100'}`}
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto flex-1 custom-note-scrollbar">
          <pre className={`text-xs leading-relaxed font-sans whitespace-pre-wrap select-text ${mutedClass}`}>
            {data.content}
          </pre>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-stone-200 dark:border-zinc-800 flex justify-end">
          <button
            onClick={onClose}
            className="h-10 px-5 rounded-xl bg-indigo-600 text-white text-xs font-black"
          >
            {lang === 'tr' ? 'Kapat' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
}
